packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/api-contract'
  - 'packages/types'
  - 'packages/design-system'
  - 'packages/utils'
  - 'packages/native-bridge'
  - 'packages/shared-hooks'
  - 'packages/mobile-ui'
